import * as React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import {
  Box,
  Image,
  Center,
  Heading,
  Text,
  Flex,
  IconButton,
  Divider,
  Link as ChakraLink,
  useBreakpointValue,
  Icon
} from '@chakra-ui/react'
import { FaChevronLeft, FaChevronRight } from 'react-icons/fa'
import { Swiper, SwiperSlide } from 'swiper/react'
import SwiperCore, { Pagination, Navigation } from 'swiper/core'

interface TravelType {
  label: string
  imageSrc: string
}

export interface Continent {
  slug: string
  name: string
  description: string
  longDescription: string
  imagePathname: string
  data: {
    numberOfCountries: number
    numberOfLanguages: number
    cities100: Array<{
      cityName: string
      countryName: string
      imagePathname: string
    }>
  }
}

const travelTypes: TravelType[] = [
  { label: 'vida noturna', imageSrc: '/images/cocktail.png' },
  { label: 'praia', imageSrc: '/images/beach.png' },
  { label: 'moderno', imageSrc: '/images/building.png' },
  { label: 'clássico', imageSrc: '/images/museum.png' },
  { label: 'e mais...', imageSrc: '/images/earth.png' }
]

export const continents: Continent[] = [
  {
    slug: 'europe',
    name: 'Europa',
    description: 'O continente mais antigo',
    longDescription:
      'A Europa é, por convenção, um dos seis continentes do mundo. Compreendendo a península ocidental da Eurásia, a Europa geralmente divide-se da Ásia a leste pela divisória de águas dos montes Urais, o rio Ural, o mae Cáspio, o Cáucaso, e o mar Negro a sudeste',
    imagePathname: 'europe.png',
    data: {
      numberOfCountries: 50,
      numberOfLanguages: 60,
      cities100: [
        {
          cityName: 'Londres',
          countryName: 'Reino Unido',
          imagePathname: 'london.png'
        },
        { cityName: 'Paris', countryName: 'França', imagePathname: 'paris.png' },
        { cityName: 'Roma', countryName: 'Itália', imagePathname: 'roma.png' },
        {
          cityName: 'Praga',
          countryName: 'República Tcheca',
          imagePathname: 'praga.png'
        },
        {
          cityName: 'Amsterdã',
          countryName: 'Holanda',
          imagePathname: 'amsterda.png'
        }
      ]
    }
  },
  {
    slug: 'america',
    name: 'America',
    description: 'O continente mais legal',
    longDescription:
      'A Europa é, por convenção, um dos seis continentes do mundo. Compreendendo a península ocidental da Eurásia, a Europa geralmente divide-se da Ásia a leste pela divisória de águas dos montes Urais, o rio Ural, o mae Cáspio, o Cáucaso, e o mar Negro a sudeste',
    imagePathname: 'europe.png',
    data: {
      numberOfCountries: 50,
      numberOfLanguages: 60,
      cities100: [
        {
          cityName: 'Londres',
          countryName: 'Reino Unido',
          imagePathname: 'london.png'
        },
        { cityName: 'Paris', countryName: 'França', imagePathname: 'paris.png' },
        { cityName: 'Roma', countryName: 'Itália', imagePathname: 'roma.png' },
        {
          cityName: 'Praga',
          countryName: 'República Tcheca',
          imagePathname: 'praga.png'
        },
        {
          cityName: 'Amsterdã',
          countryName: 'Holanda',
          imagePathname: 'amsterda.png'
        }
      ]
    }
  },
  {
    slug: 'asia',
    name: 'Ásia',
    description: 'O continente mais populoso!',
    longDescription:
      'A Europa é, por convenção, um dos seis continentes do mundo. Compreendendo a península ocidental da Eurásia, a Europa geralmente divide-se da Ásia a leste pela divisória de águas dos montes Urais, o rio Ural, o mae Cáspio, o Cáucaso, e o mar Negro a sudeste',
    imagePathname: 'europe.png',
    data: {
      numberOfCountries: 50,
      numberOfLanguages: 60,
      cities100: [
        {
          cityName: 'Londres',
          countryName: 'Reino Unido',
          imagePathname: 'london.png'
        },
        { cityName: 'Paris', countryName: 'França', imagePathname: 'paris.png' },
        { cityName: 'Roma', countryName: 'Itália', imagePathname: 'roma.png' },
        {
          cityName: 'Praga',
          countryName: 'República Tcheca',
          imagePathname: 'praga.png'
        },
        {
          cityName: 'Amsterdã',
          countryName: 'Holanda',
          imagePathname: 'amsterda.png'
        }
      ]
    }
  }
]

SwiperCore.use([Pagination, Navigation])

export default function Home() {
  const isWideScreen = useBreakpointValue({ sm: false, md: true })
  const swiperInstance = React.useRef<SwiperCore>()

  return (
    <div>
      <Head>
        <title>World Trip</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Center as='header' bg='gray.50' w='100%' h='24'>
        <Image src='/images/logo.png' alt='WorldTrip logo' h={45} />
      </Center>

      <Box
        backgroundImage='/images/hero-background.png'
        backgroundSize='cover'
        p='8'
        py='12'
        position='relative'
      >
        <Box maxW={500}>
          <Heading
            color='white'
            mb='4'
            letterSpacing='tight'
            fontWeight='medium'
          >
            5 Continentes,
            <br />
            infinitas possibilidades.
          </Heading>
          <Text color='whiteAlpha.900' fontSize='lg' letterSpacing='wider'>
            Chegou a hora de tirar do papel a viagem que você sempre sonhou
          </Text>
        </Box>
        <Image
          src='/images/airplane.png'
          alt='Avião'
          position='absolute'
          display={['none', 'none', 'block']}
          w='25%'
          right='8'
          bottom={-6}
          transform='rotate(5deg)'
        />
      </Box>

      <Flex
        mt='8'
        direction={'row'}
        alignItems='center'
        justifyContent={['center', 'center', 'space-evenly']}
        mx='auto'
        flexWrap='wrap'
        maxW={1024}
      >
        {travelTypes.map((travelType) => {
          return (
            <Flex
              key={travelType.imageSrc}
              p='6'
              flex={1}
              alignItems='center'
              justifyContent='center'
              flexDirection={['row', 'row', 'column']}
            >
              {!!isWideScreen ? (
                <Image
                  src={travelType.imageSrc}
                  alt={travelType.label}
                  width='auto'
                  mb='4'
                  maxW={['12', '12', '14']}
                  height='auto'
                  mx='auto'
                />
              ) : (
                <Box borderRadius='100%' w='4' h='4' bg='#FFBA08' mr={'2'} />
              )}
              <Text
                fontWeight='semibold'
                // flex={1}
                textAlign={['left', 'left', 'center']}
                whiteSpace='nowrap'
                textOverflow='ellipsis'
              >
                {travelType.label}
              </Text>
            </Flex>
          )
        })}
      </Flex>

      <Divider
        w='16'
        borderBottomWidth={2}
        bgColor='red.400'
        margin='0 auto'
        my='8'
        borderColor='gray.900'
      />

      <Heading textAlign='center' fontWeight='medium' color='gray.600' mb='12'>
        Vamos nessa?
        <br />
        Então escolha seu continente
      </Heading>

      <Swiper
        pagination
        slidesPerView={1}
        onSwiper={(swiper) => {
          swiperInstance.current = swiper
        }}
        style={{ maxWidth: 1240, marginBottom: 32 }}
      >
        <IconButton
          aria-label='previous'
          position='absolute'
          left={0}
          zIndex={10}
          top={0}
          bottom={0}
          variant='unstyled'
          color='yellow.500'
          height='100%'
          size='lg'
          icon={<Icon as={FaChevronLeft} width={6} height={6} />}
          onClick={() => {
            swiperInstance.current.slidePrev()
          }}
        />
        <IconButton
          aria-label='previous'
          position='absolute'
          right={0}
          zIndex={10}
          top={0}
          bottom={0}
          variant='unstyled'
          color='yellow.500'
          height='100%'
          size='lg'
          icon={<Icon as={FaChevronRight} width={6} height={6} />}
          onClick={() => {
            swiperInstance.current.slideNext()
          }}
        />
        {continents.map((continent) => {
          return (
            <SwiperSlide key={continent.name}>
              <Link
                passHref
                href={{
                  pathname: '/continents/[continent]',
                  query: { continent: continent.slug }
                }}
              >
                <ChakraLink _hover={{ textDecor: 'none' }}>
                  <Center
                    flexDirection='column'
                    flex={1}
                    maxW={1240}
                    h={250}
                    backgroundImage={`/images/countries/${continent.imagePathname}`}
                  >
                    <Heading color='white' mb='4' fontSize='5xl'>
                      {continent.name}
                    </Heading>
                    <Text color='white' letterSpacing='wider' fontWeight='bold'>
                      {continent.description}
                    </Text>
                  </Center>
                </ChakraLink>
              </Link>
            </SwiperSlide>
          )
        })}
      </Swiper>
    </div>
  )
}
